import FWCore.ParameterSet.Config as cms
import os

source = cms.Source("EmptySource")

generator = cms.EDFilter("SherpaGeneratorFilter",
  maxEventsToPrint = cms.int32(0),
  filterEfficiency = cms.untracked.double(1.0),
  crossSection = cms.untracked.double(-1),
  SherpaProcess = cms.string('13TeV_ttbbjets_NLO_sherpa211'),
  SherpackLocation = cms.string('./'),
  SherpackChecksum = cms.string('dae23c16b7ef51b7ef77c5790ab9715c'),
  FetchSherpack = cms.bool(False),
  SherpaPath = cms.string('./'),
  SherpaPathPiece = cms.string('./'),
  SherpaResultDir = cms.string('Result'),
  SherpaDefaultWeight = cms.double(1.0),
  SherpaParameters = cms.PSet(parameterSets = cms.vstring(
                             "Run"),
                              Run = cms.vstring(
				" # Sherpa2.1.1(+OpenLoops1.2.2) runcard for HXSWG studies of ttbb",
				" # NLO pp->ttbb at 13TeV in the 4F scheme",
				" # last changed by Niccolo Moretti, 23.09.15",
				" # adopted for CMS tt+bb production by Marco A. Harrendorf",
				"(run){",
				" EVENT_MODE = HepMC;",
				" # avoid comix re-init after runcard modification",
				" WRITE_MAPPING_FILE 3;",
				" SPIN CORRELATIONS=1;",
				" ### Generator and integration parameters",
				" ME_SIGNAL_GENERATOR Comix Amegic LOOPGEN",
				" EVENT_GENERATION_MODE=Weighted",
				" EVENTS=100",
				" ### NLO parameters",
				" LOOPGEN:=OpenLoops",
				" OL_GENERATE_LIST=1",
				" DIPOLE_ALPHA 0.3",
				" OL_PREFIX /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/openloops/1.1.1-kpegke",
				" ### Beams for 13TeV LHC",
				" BEAM_1=2212; BEAM_ENERGY_1=6500",
				" BEAM_2=2212; BEAM_ENERGY_2=6500",
				" ###Turning on Hard Decays under advice from Sebastian",
				" HARD_DECAYS On;",
				" ### PDFs",
				" PDF_LIBRARY LHAPDFSherpa",
				" PDF_SET NNPDF30_nlo_as_0118_nf_4   # standard NNPDF30nlo 4F NLO pdfs",
				" #  PDF_SET CT10   # standard NNPDF30nlo 4F NLO pdfs",
				" #USE_PDF_ALPHAS=1                   # takes alphaS from LHApdfs(for MEs and shower)",
				" ### top and bottom masses in MEs and PS",
				" MASS[6]=172.5",
				" MASS[5] = 4.75           # b-mass parameter(4.75 or 0)",
				" MASSIVE[5]=1                 # b-mass switcher for MEs: massive(1) or massless (0)",
				" # NB: partons with MASSIVE=1 excluded from proton/light-jet container(93)",
				" STABLE[6] 0; WIDTH[6] 0;                               #",
				" ### Scale settings: mu_F=HT/2 and mu_R= ET geometric mean",
				" FSF:=1.; RSF:=1.; QSF:=1.;",
				" # SCALES METS{FSF*MU_F2}{RSF*MU_R2}{QSF*MU_Q2};",
				" SCALES VAR{0.25*H_TM2}{sqrt(MPerp(p[2])*MPerp(p[3])*MPerp(p[4])*MPerp(p[5]))}",
				" NJET:=0; LJET:=2,3,4; QCUT:=20.;",
				"}(run)",
				"(processes){",
				" Process 93 93 -> 6 -6 5 -5    # pp -> t t b b",
				" Order_EW 0                # pure QCD contributions",
				" CKKW sqr(QCUT/E_CMS);",
				" NLO_QCD_Mode MC@NLO {LJET};",
				" ME_Generator Amegic {LJET};",
				" # Integration_Error 0.10 {4,5}  ###Removed this line at Sebastian's advice, to prevent 10",
				" Loop_Generator LOOPGEN {LJET};",
				" RS_PSI_ItMin 350000           # minimum number of events per optimisation step for RS part(default is 5000)",
				" End process",
				"}(processes)",
				"(integration){",
				" FINISH_OPTIMIZATION = Off",
				"}(integration)",
				"(selector){",
				"}(selector)"
                                                  ),
                             )
)

ProductionFilterSequence = cms.Sequence(generator)

