import FWCore.ParameterSet.Config as cms

process.generator = cms.EDProducer("CloseByParticleGunProducer",
    AddAntiParticle = cms.bool(False),
    PGunParameters = cms.PSet(
        ControlledByEta = cms.bool(True),
        FlatPtGeneration = cms.bool(False),
        LogSpacedVar = cms.bool(True),
        VarMin = cms.double(1.0),
        VarMax = cms.double(1000.0),
        PartID = cms.vint32(-211),
        Delta = cms.double(10),
        MinEta = cms.double(2.0),
        MaxEta = cms.double(2.0001),
        MinPhi = cms.double(1.57),
        MaxPhi = cms.double(1.570001),
        ZMin = cms.double(320.99),
        ZMax = cms.double(321.01),
        MaxVarSpread = cms.bool(False),
        NParticles = cms.int32(1),
        OffsetFirst = cms.double(0.0),
        Overlapping = cms.bool(False),
        Pointing = cms.bool(True),
        RMax = cms.double(55.01),
        RMin = cms.double(54.99),
        RandomShoot = cms.bool(False),
        TMax = cms.double(0.05),
        TMin = cms.double(0.0),
        UseDeltaT = cms.bool(False),
    ),
    Verbosity = cms.untracked.int32(0),
    firstRun = cms.untracked.uint32(1),
    psethack = cms.string('Pions at fixed angle, energy range 1 to 1000 GeV')
)
