import FWCore.ParameterSet.Config as cms

generator = cms.EDFilter("Pythia6GeneratorFilter",
    pythiaPylistVerbosity = cms.untracked.int32(0),
    filterEfficiency = cms.untracked.double(1.0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    comEnergy = cms.double(8000.0),
    maxEventsToPrint = cms.untracked.int32(0),
    PythiaParameters = cms.PSet(
        pythiaUESettings = cms.vstring(
            'MSTJ(11)=3     ! Choice of the fragmentation function', 
            'MSTJ(22)=2     ! Decay those unstable particles', 
            'PARJ(71)=10 .  ! for which ctau  10 mm', 
            'MSTP(2)=1      ! which order running alphaS', 
            'MSTP(33)=0     ! no K factors in hard cross sections', 
            'MSTP(51)=10042 ! structure function chosen (external PDF CTEQ6L1)', 
            'MSTP(52)=2     ! work with LHAPDF', 
            'MSTP(81)=1     ! multiple parton interactions 1 is Pythia default', 
            'MSTP(82)=4     ! Defines the multi-parton model', 
            'MSTU(21)=1     ! Check on possible errors during program execution', 
            'PARP(82)=1.8387   ! pt cutoff for multiparton interactions', 
            'PARP(89)=1960. ! sqrts for which PARP82 is set', 
            'PARP(83)=0.5   ! Multiple interactions: matter distrbn parameter', 
            'PARP(84)=0.4   ! Multiple interactions: matter distribution parameter', 
            'PARP(90)=0.16  ! Multiple interactions: rescaling power', 
            'PARP(67)=2.5    ! amount of initial-state radiation', 
            'PARP(85)=1.0  ! gluon prod. mechanism in MI', 
            'PARP(86)=1.0  ! gluon prod. mechanism in MI', 
            'PARP(62)=1.25   ! ', 
            'PARP(64)=0.2    ! ', 
            'MSTP(91)=1      !', 
            'PARP(91)=2.1   ! kt distribution', 
            'PARP(93)=15.0  ! '),
        processParameters = cms.vstring(
            'MSEL      = 0     ! User defined processes', 
            'MSUB(81)  = 1     ! qqbar to QQbar', 
            'MSUB(82)  = 1     ! gg to QQbar', 
            'MSTP(7)   = 6     ! flavour = top', 
            'PMAS(6,1) = 172.5 ! top quark mass', 
            'MWID(37)=2', 
            'PMAS(37,1) = 150 ! charged Higgs mass ', 
            'MDME(41,1) = 0   ! t decay into g t', 
            'MDME(42,1) = 0   ! t decay into gamma t', 
            'MDME(43,1) = 0   ! t decay into Z0 t', 
            'MDME(44,1) = 0   ! t decay into W d', 
            'MDME(45,1) = 0   ! t decay into W s', 
            'MDME(46,1) = 3   ! t decay into W and b ', 
            'MDME(47,1) = 0   ! t decay into W b` ', 
            'MDME(48,1) = 0   ! t decay into h0 t', 
            'MDME(49,1) = 2   ! t decay into H and b ', 
            'MDME(50,1) = 0   ! t decay into ~chi_10 ~t_1', 
            'MDME(51,1) = 0   ! t decay into ~chi_20 ~t_1', 
            'MDME(52,1) = 0   ! t decay into ~chi_30 ~t_1', 
            'MDME(53,1) = 0   ! t decay into ~chi_40 ~t_1', 
            'MDME(54,1) = 0   ! t decay into ~g ~t_1', 
            'MDME(55,1) = 0   ! t decay into ~Gravitino ~t_1',
            # Switch off / on desirable channels for W-
            'MDME(190,1) = 0',
            'MDME(191,1) = 0',
            'MDME(192,1) = 0',
            'MDME(193,1) = 0',
            'MDME(194,1) = 0',
            'MDME(195,1) = 0',
            'MDME(196,1) = 0',
            'MDME(197,1) = 0',
            'MDME(198,1) = 0',
            'MDME(199,1) = 0',
            'MDME(200,1) = 0',
            'MDME(206,1) = 1 ! W decay into e nu',
            'MDME(207,1) = 1 ! W decay into mu nu',
            'MDME(208,1) = 0'),
        parameterSets = cms.vstring('pythiaUESettings', 
            'processParameters', 
            'PYUPDAParameters'),
        PYUPDAParameters = cms.vstring("PYUPDAFILE = \'Configuration/Generator/data/Pythia_H+150_cbbar_pyupda.in\' ")
    )
)
