import FWCore.ParameterSet.Config as cms

configurationMetadata = cms.untracked.PSet(
	version = cms.untracked.string('$Revision: 1.7 $'),
	name = cms.untracked.string('$Source: /local/projects/CMSSW/rep/UserCode/Pela/UEDAnalysis/MCProduction/python/HERWIGPP_LHC7TeV_mUED_900GeV_KK1_Z0_4l_cff.py,v $'),
	annotation = cms.untracked.string('Herwig++ MUED test')
)

from Configuration.GenProduction.HerwigppDefaults_cfi import *

generator = cms.EDFilter("ThePEGGeneratorFilter",
	herwigDefaultsBlock,

	configFiles = cms.vstring("MUED.model"),
	parameterSets = cms.vstring(
		'cm7TeV',
		'pdfCTEQ6L1',
		'UEDParameters',
		'UEDDecays',
		'K0BugCorrection',
		'basicSetup',
		'setParticlesStableForDetector',
	),

	UEDParameters = cms.vstring(

		'cd /Herwig/NewPhysics',

		'set MUED/Model:InverseRadius 900.*GeV',
		'set MUED/Model:LambdaR 20',
		'set MUED/Model:HiggsBoundaryMass 0.*GeV',
		'set /Herwig/Particles/h0:NominalMass 120.*GeV',

		'set HPConstructor:IncludeEW No',
		'set ThreeBodyDC:CreateDecayModes No',

		'insert HPConstructor:Incoming 0 /Herwig/Particles/g',
		'insert HPConstructor:Incoming 1 /Herwig/Particles/u',
		'insert HPConstructor:Incoming 2 /Herwig/Particles/ubar',
		'insert HPConstructor:Incoming 3 /Herwig/Particles/d',
		'insert HPConstructor:Incoming 4 /Herwig/Particles/dbar',

		'insert HPConstructor:Outgoing 0 /Herwig/Particles/KK1_u_L',
		'insert HPConstructor:Outgoing 1 /Herwig/Particles/KK1_u_Lbar',
		'insert HPConstructor:Outgoing 2 /Herwig/Particles/KK1_d_L',
		'insert HPConstructor:Outgoing 3 /Herwig/Particles/KK1_d_Lbar',
		'insert HPConstructor:Outgoing 4 /Herwig/Particles/KK1_u_R',
		'insert HPConstructor:Outgoing 5 /Herwig/Particles/KK1_u_Rbar',
		'insert HPConstructor:Outgoing 6 /Herwig/Particles/KK1_d_R',
		'insert HPConstructor:Outgoing 7 /Herwig/Particles/KK1_d_Rbar',
		'insert HPConstructor:Outgoing 8 /Herwig/Particles/KK1_g',

	),

	UEDDecays = cms.vstring(

		'insert DecayConstructor:DisableModes 0 h0->b,bbar;',
		'insert DecayConstructor:DisableModes 1 h0->c,cbar;',
		'insert DecayConstructor:DisableModes 2 h0->mu-,mu+;',
		'insert DecayConstructor:DisableModes 3 h0->tau-,tau+;',
		'insert DecayConstructor:DisableModes 4 h0->d,dbar;',
		'insert DecayConstructor:DisableModes 5 h0->s,sbar;',
		'insert DecayConstructor:DisableModes 6 h0->Z0,d,dbar;',
		'insert DecayConstructor:DisableModes 7 h0->Z0,u,ubar;',
		'insert DecayConstructor:DisableModes 8 h0->Z0,s,sbar;',
		'insert DecayConstructor:DisableModes 9 h0->Z0,c,cbar;',
		'insert DecayConstructor:DisableModes 10 h0->Z0,b,bbar;',
		'insert DecayConstructor:DisableModes 11 h0->Z0,e-,e+;',
		'insert DecayConstructor:DisableModes 12 h0->W+,nu_ebar,e-;',
		'insert DecayConstructor:DisableModes 13 h0->W-,nu_e,e+;',
		'insert DecayConstructor:DisableModes 14 h0->Z0,mu-,mu+;',
		'insert DecayConstructor:DisableModes 15 h0->W+,nu_mubar,mu-;',
		'insert DecayConstructor:DisableModes 16 h0->W-,nu_mu,mu+;',
		'insert DecayConstructor:DisableModes 17 h0->Z0,tau-,tau+;',
		'insert DecayConstructor:DisableModes 18 h0->W+,nu_taubar,tau-;',
		'insert DecayConstructor:DisableModes 19 h0->W-,nu_tau,tau+;',
		'insert DecayConstructor:DisableModes 20 h0->W-,u,dbar;',
		'insert DecayConstructor:DisableModes 21 h0->W-,sbar,u;',
		'insert DecayConstructor:DisableModes 22 h0->W-,c,dbar;',
		'insert DecayConstructor:DisableModes 23 h0->W-,c,sbar;',
		'insert DecayConstructor:DisableModes 24 h0->W-,bbar,c;',
		'insert DecayConstructor:DisableModes 25 h0->W+,ubar,d;',
		'insert DecayConstructor:DisableModes 26 h0->W+,cbar,d;',
		'insert DecayConstructor:DisableModes 27 h0->W+,s,ubar;',
		'insert DecayConstructor:DisableModes 28 h0->W+,cbar,s;',
		'insert DecayConstructor:DisableModes 29 h0->W+,b,cbar;',
		'insert DecayConstructor:DisableModes 30 h0->Z0,nu_e,nu_ebar;',
		'insert DecayConstructor:DisableModes 31 h0->Z0,nu_mu,nu_mubar;',
		'insert DecayConstructor:DisableModes 32 h0->Z0,nu_tau,nu_taubar;',

		'insert DecayConstructor:DisableModes 33 KK1_H+->KK1_nu_tauL,tau+;',
		'insert DecayConstructor:DisableModes 34 KK1_H+->KK1_tau_1+,nu_tau;',
		'insert DecayConstructor:DisableModes 35 KK1_H+->KK1_tau_2+,nu_tau;',
		'insert DecayConstructor:DisableModes 36 KK1_H+->KK1_gamma,nu_tau,tau+;',

		'insert DecayConstructor:DisableModes 37 KK1_A0->KK1_tau_1+,tau-;',
		'insert DecayConstructor:DisableModes 38 KK1_A0->KK1_tau_1-,tau+;',
		'insert DecayConstructor:DisableModes 39 KK1_A0->KK1_tau_2+,tau-;',
		'insert DecayConstructor:DisableModes 40 KK1_A0->KK1_tau_2-,tau+;',
		'insert DecayConstructor:DisableModes 41 KK1_A0->KK1_gamma,tau-,tau+;',

		'insert DecayConstructor:DisableModes 42 KK1_h0->KK1_tau_1+,tau-;',
		'insert DecayConstructor:DisableModes 43 KK1_h0->KK1_tau_1-,tau+;',
		'insert DecayConstructor:DisableModes 44 KK1_h0->KK1_tau_2+,tau-;',
		'insert DecayConstructor:DisableModes 45 KK1_h0->KK1_tau_2-,tau+;',
		'insert DecayConstructor:DisableModes 46 KK1_h0->KK1_A0,tau-,tau+;',
		'insert DecayConstructor:DisableModes 47 KK1_h0->KK1_A0,d,dbar;',
		'insert DecayConstructor:DisableModes 48 KK1_h0->KK1_A0,u,ubar;',
		'insert DecayConstructor:DisableModes 49 KK1_h0->KK1_A0,s,sbar;',
		'insert DecayConstructor:DisableModes 50 KK1_h0->KK1_A0,c,cbar;',
		'insert DecayConstructor:DisableModes 51 KK1_h0->KK1_A0,e-,e+;',
		'insert DecayConstructor:DisableModes 52 KK1_h0->KK1_A0,nu_e,nu_ebar;',
		'insert DecayConstructor:DisableModes 53 KK1_h0->KK1_A0,mu-,mu+;',
		'insert DecayConstructor:DisableModes 54 KK1_h0->KK1_A0,nu_mu,nu_mubar;',
		'insert DecayConstructor:DisableModes 55 KK1_h0->KK1_A0,nu_tau,nu_taubar;',

		'insert DecayConstructor:DisableModes 56 KK1_W+->KK1_e_L+,nu_e;',
		'insert DecayConstructor:DisableModes 57 KK1_W+->KK1_nu_eL,e+;',
		'insert DecayConstructor:DisableModes 58 KK1_W+->KK1_mu_L+,nu_mu;',
		'insert DecayConstructor:DisableModes 59 KK1_W+->KK1_nu_muL,mu+;',
		'insert DecayConstructor:DisableModes 60 KK1_W+->KK1_tau_1+,nu_tau;',
		'insert DecayConstructor:DisableModes 61 KK1_W+->KK1_nu_tauL,tau+;',
		'insert DecayConstructor:DisableModes 62 KK1_W+->KK1_gamma,u,dbar;',
		'insert DecayConstructor:DisableModes 63 KK1_W+->KK1_gamma,c,sbar;',
		'insert DecayConstructor:DisableModes 64 KK1_W+->KK1_gamma,nu_e,e+;',
		'insert DecayConstructor:DisableModes 65 KK1_W+->KK1_gamma,nu_mu,mu+;',
		'insert DecayConstructor:DisableModes 66 KK1_W+->KK1_gamma,nu_tau,tau+;',

		'insert DecayConstructor:DisableModes 67 KK1_Z0->KK1_nu_eLbar,nu_e;',
		'insert DecayConstructor:DisableModes 68 KK1_Z0->KK1_nu_eL,nu_ebar;',
		'insert DecayConstructor:DisableModes 69 KK1_Z0->KK1_nu_muLbar,nu_mu;',
		'insert DecayConstructor:DisableModes 70 KK1_Z0->KK1_nu_muL,nu_mubar;',
		'insert DecayConstructor:DisableModes 71 KK1_Z0->KK1_tau_1+,tau-;',
		'insert DecayConstructor:DisableModes 72 KK1_Z0->KK1_tau_1-,tau+;',
		'insert DecayConstructor:DisableModes 73 KK1_Z0->KK1_tau_2+,tau-;',
		'insert DecayConstructor:DisableModes 74 KK1_Z0->KK1_tau_2-,tau+;',
		'insert DecayConstructor:DisableModes 75 KK1_Z0->KK1_nu_tauLbar,nu_tau;',
		'insert DecayConstructor:DisableModes 76 KK1_Z0->KK1_nu_tauL,nu_taubar;',

		'insert DecayConstructor:DisableModes 77 KK1_g->KK1_s_Lbar,s;',
		'insert DecayConstructor:DisableModes 78 KK1_g->KK1_s_L,sbar;',
		'insert DecayConstructor:DisableModes 79 KK1_g->KK1_c_Lbar,c;',
		'insert DecayConstructor:DisableModes 80 KK1_g->KK1_c_L,cbar;',
		'insert DecayConstructor:DisableModes 81 KK1_g->KK1_b_1bar,b;',
		'insert DecayConstructor:DisableModes 82 KK1_g->KK1_b_1,bbar;',
		'insert DecayConstructor:DisableModes 83 KK1_g->KK1_s_Rbar,s;',
		'insert DecayConstructor:DisableModes 84 KK1_g->KK1_s_R,sbar;',
		'insert DecayConstructor:DisableModes 85 KK1_g->KK1_c_Rbar,c;',
		'insert DecayConstructor:DisableModes 86 KK1_g->KK1_c_R,cbar;',
		'insert DecayConstructor:DisableModes 87 KK1_g->KK1_b_2bar,b;',
		'insert DecayConstructor:DisableModes 88 KK1_g->KK1_b_2,bbar;',

		'insert DecayConstructor:DisableModes 89 KK1_tau_2-->KK1_gamma,tau-;',

		'insert DecayConstructor:DisableModes 90 KK1_nu_tauL->KK1_gamma,nu_tau;',
		'insert DecayConstructor:DisableModes 91 KK1_nu_tauL->KK1_H+,tau-;',

		'insert DecayConstructor:DisableModes 92 KK1_tau_1-->KK1_gamma,tau-;',
		'insert DecayConstructor:DisableModes 93 KK1_tau_1-->KK1_A0,tau-;',
		'insert DecayConstructor:DisableModes 94 KK1_tau_1-->KK1_H-,nu_tau;',

		'insert DecayConstructor:DisableModes 95 KK1_nu_muL->KK1_gamma,nu_mu;',

		'insert DecayConstructor:DisableModes 96 KK1_nu_eL->KK1_gamma,nu_e;',

		'insert DecayConstructor:DisableModes 97 KK1_t_2->KK1_H+,b;',
		'insert DecayConstructor:DisableModes 98 KK1_t_2->KK1_gamma,W+,b;',
		'insert DecayConstructor:DisableModes 99 KK1_t_2->KK1_nu_tauL,tau+,b;',
		'insert DecayConstructor:DisableModes 100 KK1_t_2->KK1_tau_1+,nu_tau,b;',

		'insert DecayConstructor:DisableModes 101 KK1_b_2->KK1_gamma,b;',
		'insert DecayConstructor:DisableModes 102 KK1_b_2->KK1_Z0,b;',
		'insert DecayConstructor:DisableModes 103 KK1_b_2->KK1_h0,b;',
		'insert DecayConstructor:DisableModes 104 KK1_b_2->KK1_A0,b;',
		'insert DecayConstructor:DisableModes 105 KK1_b_2->KK1_e_L+,e-,b;',
		'insert DecayConstructor:DisableModes 106 KK1_b_2->KK1_e_L-,e+,b;',
		'insert DecayConstructor:DisableModes 107 KK1_b_2->KK1_e_R+,e-,b;',
		'insert DecayConstructor:DisableModes 108 KK1_b_2->KK1_e_R-,e+,b;',
		'insert DecayConstructor:DisableModes 109 KK1_b_2->KK1_nu_eLbar,nu_e,b;',
		'insert DecayConstructor:DisableModes 110 KK1_b_2->KK1_nu_eL,nu_ebar,b;',
		'insert DecayConstructor:DisableModes 111 KK1_b_2->KK1_mu_L+,mu-,b;',
		'insert DecayConstructor:DisableModes 112 KK1_b_2->KK1_mu_L-,mu+,b;',
		'insert DecayConstructor:DisableModes 113 KK1_b_2->KK1_mu_R+,mu-,b;',
		'insert DecayConstructor:DisableModes 114 KK1_b_2->KK1_mu_R-,mu+,b;',
		'insert DecayConstructor:DisableModes 115 KK1_b_2->KK1_nu_muLbar,nu_mu,b;',
		'insert DecayConstructor:DisableModes 116 KK1_b_2->KK1_nu_muL,nu_mubar,b;',
		'insert DecayConstructor:DisableModes 117 KK1_b_2->KK1_tau_1+,tau-,b;',
		'insert DecayConstructor:DisableModes 118 KK1_b_2->KK1_tau_1-,tau+,b;',
		'insert DecayConstructor:DisableModes 119 KK1_b_2->KK1_tau_2+,tau-,b;',
		'insert DecayConstructor:DisableModes 120 KK1_b_2->KK1_tau_2-,tau+,b;',
		'insert DecayConstructor:DisableModes 121 KK1_b_2->KK1_nu_tauLbar,nu_tau,b;',
		'insert DecayConstructor:DisableModes 122 KK1_b_2->KK1_nu_tauL,nu_taubar,b;',

		'insert DecayConstructor:DisableModes 123 KK1_c_R->KK1_gamma,c;',
		'insert DecayConstructor:DisableModes 124 KK1_c_R->KK1_Z0,c;',
		'insert DecayConstructor:DisableModes 125 KK1_c_R->KK1_e_L+,e-,c;',
		'insert DecayConstructor:DisableModes 126 KK1_c_R->KK1_e_L-,e+,c;',
		'insert DecayConstructor:DisableModes 127 KK1_c_R->KK1_e_R+,e-,c;',
		'insert DecayConstructor:DisableModes 128 KK1_c_R->KK1_e_R-,e+,c;',
		'insert DecayConstructor:DisableModes 129 KK1_c_R->KK1_nu_eLbar,nu_e,c;',
		'insert DecayConstructor:DisableModes 130 KK1_c_R->KK1_nu_eL,nu_ebar,c;',
		'insert DecayConstructor:DisableModes 131 KK1_c_R->KK1_mu_L+,mu-,c;',
		'insert DecayConstructor:DisableModes 132 KK1_c_R->KK1_mu_L-,mu+,c;',
		'insert DecayConstructor:DisableModes 133 KK1_c_R->KK1_mu_R+,mu-,c;',
		'insert DecayConstructor:DisableModes 134 KK1_c_R->KK1_mu_R-,mu+,c;',
		'insert DecayConstructor:DisableModes 135 KK1_c_R->KK1_nu_muLbar,nu_mu,c;',
		'insert DecayConstructor:DisableModes 136 KK1_c_R->KK1_nu_muL,nu_mubar,c;',
		'insert DecayConstructor:DisableModes 137 KK1_c_R->KK1_tau_1+,tau-,c;',
		'insert DecayConstructor:DisableModes 138 KK1_c_R->KK1_tau_1-,tau+,c;',
		'insert DecayConstructor:DisableModes 139 KK1_c_R->KK1_tau_2+,tau-,c;',
		'insert DecayConstructor:DisableModes 140 KK1_c_R->KK1_tau_2-,tau+,c;',
		'insert DecayConstructor:DisableModes 141 KK1_c_R->KK1_nu_tauLbar,nu_tau,c;',
		'insert DecayConstructor:DisableModes 142 KK1_c_R->KK1_nu_tauL,nu_taubar,c;',

		'insert DecayConstructor:DisableModes 143 KK1_s_R->KK1_gamma,s;',
		'insert DecayConstructor:DisableModes 144 KK1_s_R->KK1_Z0,s;',
		'insert DecayConstructor:DisableModes 145 KK1_s_R->KK1_e_L+,e-,s;',
		'insert DecayConstructor:DisableModes 146 KK1_s_R->KK1_e_L-,e+,s;',
		'insert DecayConstructor:DisableModes 147 KK1_s_R->KK1_e_R+,e-,s;',
		'insert DecayConstructor:DisableModes 148 KK1_s_R->KK1_e_R-,e+,s;',
		'insert DecayConstructor:DisableModes 149 KK1_s_R->KK1_nu_eLbar,nu_e,s;',
		'insert DecayConstructor:DisableModes 150 KK1_s_R->KK1_nu_eL,nu_ebar,s;',
		'insert DecayConstructor:DisableModes 151 KK1_s_R->KK1_mu_L+,mu-,s;',
		'insert DecayConstructor:DisableModes 152 KK1_s_R->KK1_mu_L-,mu+,s;',
		'insert DecayConstructor:DisableModes 153 KK1_s_R->KK1_mu_R+,mu-,s;',
		'insert DecayConstructor:DisableModes 154 KK1_s_R->KK1_mu_R-,mu+,s;',
		'insert DecayConstructor:DisableModes 155 KK1_s_R->KK1_nu_muLbar,nu_mu,s;',
		'insert DecayConstructor:DisableModes 156 KK1_s_R->KK1_nu_muL,nu_mubar,s;',
		'insert DecayConstructor:DisableModes 157 KK1_s_R->KK1_tau_1+,tau-,s;',
		'insert DecayConstructor:DisableModes 158 KK1_s_R->KK1_tau_1-,tau+,s;',
		'insert DecayConstructor:DisableModes 159 KK1_s_R->KK1_tau_2+,tau-,s;',
		'insert DecayConstructor:DisableModes 160 KK1_s_R->KK1_tau_2-,tau+,s;',
		'insert DecayConstructor:DisableModes 161 KK1_s_R->KK1_nu_tauLbar,nu_tau,s;',
		'insert DecayConstructor:DisableModes 162 KK1_s_R->KK1_nu_tauL,nu_taubar,s;',

		'insert DecayConstructor:DisableModes 163 KK1_u_R->KK1_gamma,u;',
		'insert DecayConstructor:DisableModes 164 KK1_u_R->KK1_e_L+,e-,u;',
		'insert DecayConstructor:DisableModes 165 KK1_u_R->KK1_e_L-,e+,u;',
		'insert DecayConstructor:DisableModes 166 KK1_u_R->KK1_e_R+,e-,u;',
		'insert DecayConstructor:DisableModes 167 KK1_u_R->KK1_e_R-,e+,u;',
		'insert DecayConstructor:DisableModes 168 KK1_u_R->KK1_nu_eLbar,nu_e,u;',
		'insert DecayConstructor:DisableModes 169 KK1_u_R->KK1_nu_eL,nu_ebar,u;',
		'insert DecayConstructor:DisableModes 170 KK1_u_R->KK1_mu_L+,mu-,u;',
		'insert DecayConstructor:DisableModes 171 KK1_u_R->KK1_mu_L-,mu+,u;',
		'insert DecayConstructor:DisableModes 172 KK1_u_R->KK1_mu_R+,mu-,u;',
		'insert DecayConstructor:DisableModes 173 KK1_u_R->KK1_mu_R-,mu+,u;',
		'insert DecayConstructor:DisableModes 174 KK1_u_R->KK1_nu_muLbar,nu_mu,u;',
		'insert DecayConstructor:DisableModes 175 KK1_u_R->KK1_nu_muL,nu_mubar,u;',
		'insert DecayConstructor:DisableModes 176 KK1_u_R->KK1_tau_1+,tau-,u;',
		'insert DecayConstructor:DisableModes 177 KK1_u_R->KK1_tau_1-,tau+,u;',
		'insert DecayConstructor:DisableModes 178 KK1_u_R->KK1_tau_2+,tau-,u;',
		'insert DecayConstructor:DisableModes 179 KK1_u_R->KK1_tau_2-,tau+,u;',
		'insert DecayConstructor:DisableModes 180 KK1_u_R->KK1_nu_tauLbar,nu_tau,u;',
		'insert DecayConstructor:DisableModes 181 KK1_u_R->KK1_nu_tauL,nu_taubar,u;',

		'insert DecayConstructor:DisableModes 182 KK1_d_R->KK1_gamma,d;',
		'insert DecayConstructor:DisableModes 183 KK1_d_R->KK1_e_L+,e-,d;',
		'insert DecayConstructor:DisableModes 184 KK1_d_R->KK1_e_L-,e+,d;',
		'insert DecayConstructor:DisableModes 185 KK1_d_R->KK1_e_R+,e-,d;',
		'insert DecayConstructor:DisableModes 186 KK1_d_R->KK1_e_R-,e+,d;',
		'insert DecayConstructor:DisableModes 187 KK1_d_R->KK1_nu_eLbar,nu_e,d;',
		'insert DecayConstructor:DisableModes 188 KK1_d_R->KK1_nu_eL,nu_ebar,d;',
		'insert DecayConstructor:DisableModes 189 KK1_d_R->KK1_mu_L+,mu-,d;',
		'insert DecayConstructor:DisableModes 190 KK1_d_R->KK1_mu_L-,mu+,d;',
		'insert DecayConstructor:DisableModes 191 KK1_d_R->KK1_mu_R+,mu-,d;',
		'insert DecayConstructor:DisableModes 192 KK1_d_R->KK1_mu_R-,mu+,d;',
		'insert DecayConstructor:DisableModes 193 KK1_d_R->KK1_nu_muLbar,nu_mu,d;',
		'insert DecayConstructor:DisableModes 194 KK1_d_R->KK1_nu_muL,nu_mubar,d;',
		'insert DecayConstructor:DisableModes 195 KK1_d_R->KK1_tau_1+,tau-,d;',
		'insert DecayConstructor:DisableModes 196 KK1_d_R->KK1_tau_1-,tau+,d;',
		'insert DecayConstructor:DisableModes 197 KK1_d_R->KK1_tau_2+,tau-,d;',
		'insert DecayConstructor:DisableModes 198 KK1_d_R->KK1_tau_2-,tau+,d;',
		'insert DecayConstructor:DisableModes 199 KK1_d_R->KK1_nu_tauLbar,nu_tau,d;',
		'insert DecayConstructor:DisableModes 200 KK1_d_R->KK1_nu_tauL,nu_taubar,d;',

		'insert DecayConstructor:DisableModes 201 KK1_t_1->KK1_W+,d;',
		'insert DecayConstructor:DisableModes 202 KK1_t_1->KK1_W+,s;',
		'insert DecayConstructor:DisableModes 203 KK1_t_1->KK1_W+,b;',

		'insert DecayConstructor:DisableModes 204 KK1_t_1->KK1_H+,b;',
		'insert DecayConstructor:DisableModes 205 KK1_b_1->KK1_W-,u;',
		'insert DecayConstructor:DisableModes 206 KK1_b_1->KK1_W-,c;',
		'insert DecayConstructor:DisableModes 207 KK1_b_1->KK1_gamma,b;',
		'insert DecayConstructor:DisableModes 208 KK1_b_1->KK1_Z0,b;',
		'insert DecayConstructor:DisableModes 209 KK1_b_1->KK1_h0,b;',
		'insert DecayConstructor:DisableModes 210 KK1_b_1->KK1_A0,b;',

		'insert DecayConstructor:DisableModes 211 KK1_c_L->KK1_W+,d;',
		'insert DecayConstructor:DisableModes 212 KK1_c_L->KK1_W+,s;',
		'insert DecayConstructor:DisableModes 213 KK1_c_L->KK1_W+,b;',
		'insert DecayConstructor:DisableModes 214 KK1_c_L->KK1_gamma,c;',
		'insert DecayConstructor:DisableModes 215 KK1_c_L->KK1_Z0,c;',
		'insert DecayConstructor:DisableModes 216 KK1_c_L->KK1_e_R+,e-,c;',
		'insert DecayConstructor:DisableModes 217 KK1_c_L->KK1_e_R-,e+,c;',
		'insert DecayConstructor:DisableModes 218 KK1_c_L->KK1_mu_R+,mu-,c;',
		'insert DecayConstructor:DisableModes 219 KK1_c_L->KK1_mu_R-,mu+,c;',
		'insert DecayConstructor:DisableModes 220 KK1_c_L->KK1_tau_2+,tau-,c;',
		'insert DecayConstructor:DisableModes 221 KK1_c_L->KK1_tau_2-,tau+,c;',
		'insert DecayConstructor:DisableModes 222 KK1_s_L->KK1_W-,u;',
		'insert DecayConstructor:DisableModes 223 KK1_s_L->KK1_W-,c;',
		'insert DecayConstructor:DisableModes 224 KK1_s_L->KK1_gamma,s;',
		'insert DecayConstructor:DisableModes 225 KK1_s_L->KK1_Z0,s;',

		'insert DecayConstructor:DisableModes 226 KK1_u_L->KK1_W+,d;',
		'insert DecayConstructor:DisableModes 227 KK1_u_L->KK1_W+,s;',
		'insert DecayConstructor:DisableModes 228 KK1_u_L->KK1_W+,b;',
		'insert DecayConstructor:DisableModes 229 KK1_u_L->KK1_gamma,u;',
		'insert DecayConstructor:DisableModes 230 KK1_u_L->KK1_e_R+,e-,u;',
		'insert DecayConstructor:DisableModes 231 KK1_u_L->KK1_e_R-,e+,u;',
		'insert DecayConstructor:DisableModes 232 KK1_u_L->KK1_mu_R+,mu-,u;',
		'insert DecayConstructor:DisableModes 233 KK1_u_L->KK1_mu_R-,mu+,u;',
		'insert DecayConstructor:DisableModes 234 KK1_u_L->KK1_tau_2+,tau-,u;',
		'insert DecayConstructor:DisableModes 235 KK1_u_L->KK1_tau_2-,tau+,u;',

		'insert DecayConstructor:DisableModes 236 KK1_d_L->KK1_W-,u;',
		'insert DecayConstructor:DisableModes 237 KK1_d_L->KK1_W-,c;',
		'insert DecayConstructor:DisableModes 238 KK1_d_L->KK1_gamma,d;'

	),

	K0BugCorrection = cms.vstring(

		'set /Herwig/Particles/Kbar0:Width 1e300*GeV',
		'set /Herwig/Particles/K0:Width 1e300*GeV'

	),


	crossSection = cms.untracked.double(0.000332e+00),
	filterEfficiency = cms.untracked.double(1.0),
)

ProductionFilterSequence = cms.Sequence(generator)

