import FWCore.ParameterSet.Config as cms

from Configuration.GenProduction.PythiaUESettings_cfi import *
generator = cms.EDFilter("Pythia6GeneratorFilter",   
    pythiaPylistVerbosity = cms.untracked.int32(0),
    filterEfficiency = cms.untracked.double(1.0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    comEnergy = cms.double(10000.0),
    maxEventsToPrint = cms.untracked.int32(0),
    crossSection  = cms.untracked.double(0.0001898),
    PythiaParameters = cms.PSet(
        pythiaUESettings = cms.vstring('MSTJ(11)=3     ! Choice of the fragmentation function', 
            'MSTJ(22)=2     ! Decay those unstable particles', 
            'PARJ(71)=10 .  ! for which ctau  10 mm', 
            'MSTP(2)=1      ! which order running alphaS', 
            'MSTP(33)=0     ! no K factors in hard cross sections', 
            'MSTP(51)=10042 ! structure function chosen (external PDF CTEQ6L1)', 
            'MSTP(52)=2     ! work with LHAPDF', 
            'MSTP(81)=1     ! multiple parton interactions 1 is Pythia default', 
            'MSTP(82)=4     ! Defines the multi-parton model', 
            'MSTU(21)=1     ! Check on possible errors during program execution', 
            'PARP(82)=1.8387   ! pt cutoff for multiparton interactions', 
            'PARP(89)=1960. ! sqrts for which PARP82 is set', 
            'PARP(83)=0.5   ! Multiple interactions: matter distrbn parameter', 
            'PARP(84)=0.4   ! Multiple interactions: matter distribution parameter', 
            'PARP(90)=0.16  ! Multiple interactions: rescaling power', 
            'PARP(67)=2.5    ! amount of initial-state radiation', 
            'PARP(85)=1.0  ! gluon prod. mechanism in MI', 
            'PARP(86)=1.0  ! gluon prod. mechanism in MI', 
            'PARP(62)=1.25   ! ', 
            'PARP(64)=0.2    ! ', 
            'MSTP(91)=1      !', 
            'PARP(91)=2.1   ! kt distribution', 
            'PARP(93)=15.0  ! '),
        processParameters = cms.vstring('PMAS(347,1)= 1500.         !mass of RS Graviton', 
            'PARP(50) = 0.054           ! 0.054 == c=0.01 (k/M_PL=0.01)', 
            'MSEL=0                    !(D=1) to select between full user control (0, then use MSUB) and some preprogrammed alternative', 
            'MSUB(391)=1               ! q qbar -> G* ', 
            'MSUB(392)=1               ! g g -> G*', 
            'MDME(4084,1)=0            ! d dbar', 
            'MDME(4085,1)=0            ! u ubar', 
            'MDME(4086,1)=0            ! s sbar', 
            'MDME(4087,1)=0            ! c cbar', 
            'MDME(4088,1)=0            ! b bbar', 
            'MDME(4089,1)=0            ! t tbar', 
            'MDME(4090,1)=-1            ! bprime bprimebar', 
            'MDME(4091,1)=-1            ! tprime tprimebar', 
            'MDME(4092,1)=1            ! e+ e-', 
            'MDME(4093,1)=0            ! nu_e nu_ebar', 
            'MDME(4094,1)=0            ! mu- mu+', 
            'MDME(4095,1)=0            ! nu_mu nu_mubar', 
            'MDME(4096,1)=0            ! tau- tau+', 
            'MDME(4097,1)=0            ! nu_tau  nu_taubar', 
            'MDME(4098,1)=-1            ! tauprime- tauprime+ ', 
            'MDME(4099,1)=-1            ! nuprime_tau nuprime_taubar ', 
            'MDME(4100,1)=0            ! g  g  ', 
            'MDME(4101,1)=0            ! gamma gamma ', 
            'MDME(4102,1)=0            ! Z Z', 
            'MDME(4103,1)=0            ! W W', 
            'CKIN(3)=-1.          ! minimum pt hat for hard interactions', 
            'CKIN(4)=-1.          ! maximum pt hat for hard interactions'),

        parameterSets = cms.vstring('pythiaUESettings', 
            'processParameters')
    )
)
ProductionFilterSequence = cms.Sequence(generator)
