import FWCore.ParameterSet.Config as cms

source = cms.Source("EmptySource")

generator = cms.EDFilter("SherpaGeneratorFilter",
  maxEventsToPrint = cms.untracked.int32(0),
  filterEfficiency = cms.untracked.double(1.0),
  crossSection = cms.untracked.double(-1),
  libDir    = cms.untracked.string('SherpaRun'),
  resultDir = cms.untracked.string('Result'),
  SherpaParameters = cms.PSet(parameterSets = cms.vstring(
                             "Analysis",
                             "Run"),
                              Analysis = cms.vstring(
				" BEGIN_ANALYSIS {",
				" LEVEL Hadron;",
				" PATH_PIECE Norm/;",
				" Statistics FinalState;",
				"} END_ANALYSIS;"
                                                  ),
                              Run = cms.vstring(
				"(run){",
				" EVENTS = 100;",
				" ANALYSIS = 0;",
				" EVENT_MODE = HepMC",
				"}(run)",
				"(beam){",
				" BEAM_1          = 2212",
				" BEAM_ENERGY_1   = 3500.",
				" BEAM_2          = 2212",
				" BEAM_ENERGY_2   = 3500.",
				"}(beam)",
				"(processes){",
				" Process 93 93 -> 93 39;",
				" Print_Graphs : Process;",
				" End process;",
				"}(processes)",
				"(selector){",
				" JetFinder   sqr(20/E_CMS) 1.",
				" ET 93 50 E_CMS",
				"}(selector)",
				"(model){",
				" MODEL                 = ADD",
				" EW_SCHEME             = 0",
				" ALPHAS(MZ)            = 0.118",
				" ALPHAS(default)       = 0.0800",
				" ORDER_ALPHAS          = 1",
				" 1/ALPHAQED(0)         = 137.036",
				" 1/ALPHAQED(default)   = 132.51",
				" SIN2THETAW            = 0.2222",
				" VEV                   = 246.",
				" LAMBDA                = 0.47591",
				" CKMORDER              = 0",
				" CABIBBO               = 0.22",
				" A                     = 0.85",
				" RHO                   = 0.50",
				" ETA                   = 0.50",
				" SLHA_INPUT            = LesHouches_SPS1A.dat",
				" N_ED                  = 2",
				" G_NEWTON              = 6.707e-39",
				" M_S                   = 2.0e3",
				" M_CUT                 = 2.0e3",
				" KK_CONVENTION         = 5",
				" STABLE[15]=0",
				" MASS[39] = 100.",
				" MASS[40] = 100.",
				"}(model)",
				"(me){",
				" ME_SIGNAL_GENERATOR = Amegic",
				"}(me)",
				"(fragmentation){",
				" FRAGMENTATION=Off;",
				"}(fragmentation)",
				"(mi){",
				" MI_HANDLER   = Amisic",
				"}(mi)",
				"(analysis){",
				" BEGIN_ANALYSIS {",
				" LEVEL  MEs Showers",
				" PT    39  0. 2000. 100 LinErr FinalState",
				"} END_ANALYSIS",
				"}(analysis)"
                                                  ),
                             )
)

ProductionFilterSequence = cms.Sequence(generator)

